# 使用 air 进行热重载 (app = api | mail)
dev app:
    air -c {{app}}.air.toml

# 运行程序 (app = api | mail)
run app:
    go run cmd/{{app}}/main.go

# 创建数据库迁移文件
new-migration name:
    goose -s create {{name}} sql

# 数据库迁移 (op = up | down)
migrate op:
    goose {{op}}

# 插入随机用户
seed-users n:
    go run cmd/seed/main.go -op 1 -n {{n}}

# 插入随机班表模板
seed-schedule-templates n:
    go run cmd/seed/main.go -op 2 -n {{n}}

# 插入随机排班计划
seed-schedule-plans n:
    go run cmd/seed/main.go -op 3 -n {{n}}
